// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ5gXJP9M6vfB9IsZ4OrV6-cQ8pICkbko',
    appId: '1:446248110336:web:2f8d8b46e79d618f2e8be5',
    messagingSenderId: '446248110336',
    projectId: 'volt-wheels-98a59',
    authDomain: 'volt-wheels-98a59.firebaseapp.com',
    storageBucket: 'volt-wheels-98a59.appspot.com',
    measurementId: 'G-GZLMMJJT3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx3o91CBCMtdhKdNI8Q0ewiBnBbz23dwk',
    appId: '1:446248110336:android:2119164108c1e5732e8be5',
    messagingSenderId: '446248110336',
    projectId: 'volt-wheels-98a59',
    storageBucket: 'volt-wheels-98a59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxQU2NIh5BTg2u5ghq7HDHSHOPYgoCk2A',
    appId: '1:446248110336:ios:576dff43cbdd47be2e8be5',
    messagingSenderId: '446248110336',
    projectId: 'volt-wheels-98a59',
    storageBucket: 'volt-wheels-98a59.appspot.com',
    iosBundleId: 'com.voltwheels.mobile.voltwheelsMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxQU2NIh5BTg2u5ghq7HDHSHOPYgoCk2A',
    appId: '1:446248110336:ios:576dff43cbdd47be2e8be5',
    messagingSenderId: '446248110336',
    projectId: 'volt-wheels-98a59',
    storageBucket: 'volt-wheels-98a59.appspot.com',
    iosBundleId: 'com.voltwheels.mobile.voltwheelsMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQ5gXJP9M6vfB9IsZ4OrV6-cQ8pICkbko',
    appId: '1:446248110336:web:131238f2fd8a840e2e8be5',
    messagingSenderId: '446248110336',
    projectId: 'volt-wheels-98a59',
    authDomain: 'volt-wheels-98a59.firebaseapp.com',
    storageBucket: 'volt-wheels-98a59.appspot.com',
    measurementId: 'G-6S9ZPBZZ4Z',
  );
}
